#!/bin/bash
yum update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd
usermod -a -G appache ec2-user
chown -R ec2-user:apache /var/www
chmod 2775 /var/www
echo "hello world from $(hostname)" >/var/www/html/index.html
